"""
Defeasible conversion of definite logic programs.

Implements Definition 9 (defeasible conversion) from paper.tex lines 572-579.

Author: Patrick Cooper
Date: 2026-02-11
"""

from typing import Set, Dict
from blanc.core.theory import Theory, Rule, RuleType
from blanc.generation.partition import PartitionFunction


def phi_kappa(theory: Theory, kappa: PartitionFunction) -> Theory:
    """
    Defeasible conversion φ_κ(Π).
    
    Definition 9 (paper.tex lines 572-579):
    Given partition κ: Π → {s, d}, construct D = (F_κ, Rs^κ, Rd^κ, ∅, ∅):
    
    F_κ = {h | (h :-) ∈ Π, κ(h :-) = s}
    Rs^κ = {b1,...,bn → h | (h :- b1,...,bn) ∈ Π, n > 0, κ(...) = s}
    Rd^κ = {b1,...,bn ⇒ h | (h :- b1,...,bn) ∈ Π, κ(...) = d}
          ∪ {⊤ ⇒ h | (h :-) ∈ Π, κ(h :-) = d}
    
    The conversion makes epistemic commitments explicit:
    - Every conclusion has a traceable support set
    - Every default is revisable
    - Every element's criticality is computable
    
    Proposition 1 (line 743): When κ ≡ s (all strict),
    q ∈ M_Π ⟺ D_κ ⊢Δ q (conservative conversion).
    
    Args:
        theory: Source theory (treated as definite logic program)
        kappa: Partition function classifying clauses as strict or defeasible
    
    Returns:
        Converted defeasible theory with empty defeater and superiority sets
    
    Example:
        >>> from blanc.generation.partition import partition_rule
        >>> base_theory = Theory()
        >>> base_theory.add_fact("bird(tweety)")
        >>> base_theory.add_rule(Rule(head="flies(X)", body=("bird(X)",)))
        >>> 
        >>> defeasible_theory = phi_kappa(base_theory, partition_rule)
        >>> # Result: bird(tweety) is strict fact, flies rule is defeasible
    """
    converted = Theory()
    
    # Process all rules from source theory
    # Note: In the source theory, facts are represented in theory.facts
    # and also possibly as Rule objects with empty body
    
    # First, handle explicit facts
    for fact in theory.facts:
        # Create a temporary Rule object to classify
        fact_rule = Rule(head=fact, body=(), rule_type=RuleType.FACT)
        classification = kappa(fact_rule)
        
        if classification == 's':
            # F_κ: Strict fact
            converted.add_fact(fact)
        elif classification == 'd':
            # Rd^κ: Defeasible fact (⊤ ⇒ h)
            # In our representation: defeasible rule with empty body
            converted.add_rule(Rule(
                head=fact,
                body=(),
                rule_type=RuleType.DEFEASIBLE,
                label=f"df_{fact}"  # Auto-label for defeasible facts
            ))
    
    # Process non-fact rules
    for rule in theory.rules:
        if rule.is_fact:
            # Already handled above via theory.facts
            continue
        
        # Create a temporary Rule with original type for classification
        # (The partition function should see the original structure)
        temp_rule = Rule(head=rule.head, body=rule.body, rule_type=rule.rule_type)
        classification = kappa(temp_rule)
        
        if classification == 's':
            # Rs^κ: Strict rule
            converted.add_rule(Rule(
                head=rule.head,
                body=rule.body,
                rule_type=RuleType.STRICT,
                label=rule.label,
                metadata=rule.metadata
            ))
        elif classification == 'd':
            # Rd^κ: Defeasible rule
            converted.add_rule(Rule(
                head=rule.head,
                body=rule.body,
                rule_type=RuleType.DEFEASIBLE,
                label=rule.label,
                metadata=rule.metadata
            ))
    
    # Defeater set is empty by construction (Definition 9)
    # Superiority relation is empty by construction
    # These will be generated by the model (Level 3)
    
    return converted


def convert_theory_to_defeasible(
    theory: Theory,
    partition_strategy: str = "rule",
    **kwargs
) -> Theory:
    """
    Convert theory to defeasible using named partition strategy.
    
    Convenience function for common partition strategies.
    
    Args:
        theory: Source theory
        partition_strategy: One of 'leaf', 'rule', 'depth', 'random'
        **kwargs: Additional parameters for partition function
            - For 'depth': k (int) - depth threshold
            - For 'random': delta (float), seed (int)
    
    Returns:
        Converted defeasible theory
    
    Example:
        >>> theory = create_avian_biology_base()
        >>> defeasible = convert_theory_to_defeasible(theory, "rule")
    """
    from blanc.generation.partition import (
        partition_leaf,
        partition_rule,
        partition_depth,
        partition_random,
        compute_dependency_depths,
    )
    
    if partition_strategy == "leaf":
        return phi_kappa(theory, partition_leaf)
    
    elif partition_strategy == "rule":
        return phi_kappa(theory, partition_rule)
    
    elif partition_strategy == "depth":
        k = kwargs.get('k', 1)
        depths = compute_dependency_depths(theory)
        return phi_kappa(theory, partition_depth(k, depths))
    
    elif partition_strategy == "random":
        delta = kwargs.get('delta', 0.5)
        seed = kwargs.get('seed', None)
        return phi_kappa(theory, partition_random(delta, seed))
    
    else:
        raise ValueError(
            f"Unknown partition strategy: {partition_strategy}. "
            f"Available: 'leaf', 'rule', 'depth', 'random'"
        )


def _extract_predicate(atom: str) -> str:
    """Extract predicate symbol from atom."""
    # Handle negation
    if atom.startswith("~"):
        atom = atom[1:]
    
    # Extract before parentheses
    if "(" in atom:
        return atom.split("(")[0]
    return atom
