"""
LKIF Core Legal KB - Extracted Rules

Extracted from LKIF Core ontology (University of Amsterdam).
Expert-curated legal ontology from ESTRELLA project.

Classes: 227
Rules: 201

Citation: Hoekstra, R., Boer, A., van den Berg, K.
          LKIF Core ontology.

Author: Extracted by Anonymous Authors
Date: 2026-02-12
"""

from blanc.core.theory import Theory, Rule, RuleType


def create_lkif_legal() -> Theory:
    """Create LKIF-extracted legal KB."""
    theory = Theory()

    theory.add_rule(Rule(
        head="potestative_expression(X)",
        body=("hohfeldian_power(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r0"
    ))
    theory.add_rule(Rule(
        head="potestative_expression(X)",
        body=("enabling_power(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r1"
    ))
    theory.add_rule(Rule(
        head="potestative_expression(X)",
        body=("declarative_power(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r2"
    ))
    theory.add_rule(Rule(
        head="n007bcd228177410ba099b42f05efddea(X)",
        body=("normatively_qualified(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r3"
    ))
    theory.add_rule(Rule(
        head="qualified(X)",
        body=("normatively_qualified(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r4"
    ))
    theory.add_rule(Rule(
        head="soft_law(X)",
        body=("code_of_conduct(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r5"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("code_of_conduct(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r6"
    ))
    theory.add_rule(Rule(
        head="n419c1fbcfc524b8099630ea2398e2bf6(X)",
        body=("regulation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r7"
    ))
    theory.add_rule(Rule(
        head="n84d64e58c46c415cb17e45f95cb6c74e(X)",
        body=("regulation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r8"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("regulation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r9"
    ))
    theory.add_rule(Rule(
        head="proclamation(X)",
        body=("decree(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r10"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("decree(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r11"
    ))
    theory.add_rule(Rule(
        head="n3a804a69ba75444db69c0212dd83e845(X)",
        body=("contract(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r12"
    ))
    theory.add_rule(Rule(
        head="ncbc4ae5a88f046db84e9ae235471297a(X)",
        body=("contract(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r13"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("contract(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r14"
    ))
    theory.add_rule(Rule(
        head="n2548260110ca47ec959a2a9950bd2cdf(X)",
        body=("statute(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r15"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("statute(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r16"
    ))
    theory.add_rule(Rule(
        head="n00a67e2e672649058576626810d51386(X)",
        body=("statute(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r17"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("treaty(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r18"
    ))
    theory.add_rule(Rule(
        head="international_agreement(X)",
        body=("treaty(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r19"
    ))
    theory.add_rule(Rule(
        head="n5b6efb0e5c6c453baf7687015f6b8414(X)",
        body=("code(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r20"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("code(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r21"
    ))
    theory.add_rule(Rule(
        head="n2f8f9fc5b33f47a2903b33ba3023a995(X)",
        body=("code(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r22"
    ))
    theory.add_rule(Rule(
        head="proclamation(X)",
        body=("directive(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r23"
    ))
    theory.add_rule(Rule(
        head="legal_document(X)",
        body=("directive(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r24"
    ))
    theory.add_rule(Rule(
        head="soft_law(X)",
        body=("resolution(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r25"
    ))
    theory.add_rule(Rule(
        head="international_agreement(X)",
        body=("resolution(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r26"
    ))
    theory.add_rule(Rule(
        head="soft_law(X)",
        body=("international_arbitration(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r27"
    ))
    theory.add_rule(Rule(
        head="soft_law(X)",
        body=("non_binding_international_agreement(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r28"
    ))
    theory.add_rule(Rule(
        head="international_agreement(X)",
        body=("non_binding_international_agreement(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r29"
    ))
    theory.add_rule(Rule(
        head="legal_source(X)",
        body=("soft_law(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r30"
    ))
    theory.add_rule(Rule(
        head="legal_source(X)",
        body=("proclamation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r31"
    ))
    theory.add_rule(Rule(
        head="legal_source(X)",
        body=("legal_doctrine(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r32"
    ))
    theory.add_rule(Rule(
        head="legal_source(X)",
        body=("international_agreement(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r33"
    ))
    theory.add_rule(Rule(
        head="custom(X)",
        body=("customary_law(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r34"
    ))
    theory.add_rule(Rule(
        head="legal_source(X)",
        body=("customary_law(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r35"
    ))
    theory.add_rule(Rule(
        head="document(X)",
        body=("legal_document(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r36"
    ))
    theory.add_rule(Rule(
        head="legal_source(X)",
        body=("legal_document(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r37"
    ))
    theory.add_rule(Rule(
        head="legal_source(X)",
        body=("precedent(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r38"
    ))
    theory.add_rule(Rule(
        head="disallowed(X)",
        body=("strictly_disallowed(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r39"
    ))
    theory.add_rule(Rule(
        head="disallowed(X)",
        body=("allowed_and_disallowed(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r40"
    ))
    theory.add_rule(Rule(
        head="allowed(X)",
        body=("allowed_and_disallowed(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r41"
    ))
    theory.add_rule(Rule(
        head="right(X)",
        body=("permissive_right(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r42"
    ))
    theory.add_rule(Rule(
        head="right(X)",
        body=("liberty_right(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r43"
    ))
    theory.add_rule(Rule(
        head="right(X)",
        body=("liability_right(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r44"
    ))
    theory.add_rule(Rule(
        head="right(X)",
        body=("obligative_right(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r45"
    ))
    theory.add_rule(Rule(
        head="n78d3c58e708c42cb9bde4ab6ff4bf24b(X)",
        body=("legal_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r46"
    ))
    theory.add_rule(Rule(
        head="expression(X)",
        body=("legal_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r47"
    ))
    theory.add_rule(Rule(
        head="legal_expression(X)",
        body=("qualificatory_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r48"
    ))
    theory.add_rule(Rule(
        head="legal_expression(X)",
        body=("existential_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r49"
    ))
    theory.add_rule(Rule(
        head="evaluative_proposition(X)",
        body=("evaluative_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r50"
    ))
    theory.add_rule(Rule(
        head="legal_expression(X)",
        body=("evaluative_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r51"
    ))
    theory.add_rule(Rule(
        head="legal_expression(X)",
        body=("potestative_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r52"
    ))
    theory.add_rule(Rule(
        head="legal_expression(X)",
        body=("definitional_expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r53"
    ))
    theory.add_rule(Rule(
        head="precedent(X)",
        body=("persuasive_precedent(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r54"
    ))
    theory.add_rule(Rule(
        head="precedent(X)",
        body=("mandatory_precedent(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r55"
    ))
    theory.add_rule(Rule(
        head="belief(X)",
        body=("belief_in_violation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r56"
    ))
    theory.add_rule(Rule(
        head="allowed(X)",
        body=("strictly_allowed(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r57"
    ))
    theory.add_rule(Rule(
        head="allowed(X)",
        body=("obliged(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r58"
    ))
    theory.add_rule(Rule(
        head="medium(X)",
        body=("custom(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r59"
    ))
    theory.add_rule(Rule(
        head="medium(X)",
        body=("legal_source(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r60"
    ))
    theory.add_rule(Rule(
        head="obligative_right(X)",
        body=("exclusionary_right(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r61"
    ))
    theory.add_rule(Rule(
        head="hohfeldian_power(X)",
        body=("action_power(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r62"
    ))
    theory.add_rule(Rule(
        head="hohfeldian_power(X)",
        body=("immunity(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r63"
    ))
    theory.add_rule(Rule(
        head="normatively_qualified(X)",
        body=("allowed(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r64"
    ))
    theory.add_rule(Rule(
        head="normatively_qualified(X)",
        body=("disallowed(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r65"
    ))
    theory.add_rule(Rule(
        head="problem(X)",
        body=("observation_of_violation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r66"
    ))
    theory.add_rule(Rule(
        head="qualification(X)",
        body=("norm(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r67"
    ))
    theory.add_rule(Rule(
        head="enabling_power(X)",
        body=("potestative_right(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r68"
    ))
    theory.add_rule(Rule(
        head="permission(X)",
        body=("obligation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r69"
    ))
    theory.add_rule(Rule(
        head="permission(X)",
        body=("prohibition(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r70"
    ))
    theory.add_rule(Rule(
        head="intention(X)",
        body=("disallowed_intention(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r71"
    ))
    theory.add_rule(Rule(
        head="norm(X)",
        body=("permission(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r72"
    ))
    theory.add_rule(Rule(
        head="norm(X)",
        body=("right(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r73"
    ))
    theory.add_rule(Rule(
        head="company(X)",
        body=("limited_company(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r74"
    ))
    theory.add_rule(Rule(
        head="company(X)",
        body=("public_limited_company(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r75"
    ))
    theory.add_rule(Rule(
        head="legal_person(X)",
        body=("private_legal_person(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r76"
    ))
    theory.add_rule(Rule(
        head="legal_person(X)",
        body=("public_body(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r77"
    ))
    theory.add_rule(Rule(
        head="private_legal_person(X)",
        body=("society(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r78"
    ))
    theory.add_rule(Rule(
        head="private_legal_person(X)",
        body=("corporation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r79"
    ))
    theory.add_rule(Rule(
        head="private_legal_person(X)",
        body=("company(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r80"
    ))
    theory.add_rule(Rule(
        head="private_legal_person(X)",
        body=("association(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r81"
    ))
    theory.add_rule(Rule(
        head="person(X)",
        body=("natural_person(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r82"
    ))
    theory.add_rule(Rule(
        head="nb30180d955e04e58a4c31fef84fe03e3(X)",
        body=("mandate(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r83"
    ))
    theory.add_rule(Rule(
        head="public_act(X)",
        body=("mandate(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r84"
    ))
    theory.add_rule(Rule(
        head="n5464c1441cb64fbfa74b5e4d0e7a9660(X)",
        body=("mandate(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r85"
    ))
    theory.add_rule(Rule(
        head="nb8233e8a85194405915619669d44f09e(X)",
        body=("delegation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r86"
    ))
    theory.add_rule(Rule(
        head="ne409ff8942914380a7e458d04d6e267e(X)",
        body=("delegation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r87"
    ))
    theory.add_rule(Rule(
        head="public_act(X)",
        body=("delegation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r88"
    ))
    theory.add_rule(Rule(
        head="legal_speech_act(X)",
        body=("delegation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r89"
    ))
    theory.add_rule(Rule(
        head="nfcad2c6f20d9491c820449e4f088fd6c(X)",
        body=("act_of_law(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r90"
    ))
    theory.add_rule(Rule(
        head="public_act(X)",
        body=("act_of_law(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r91"
    ))
    theory.add_rule(Rule(
        head="legal_speech_act(X)",
        body=("act_of_law(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r92"
    ))
    theory.add_rule(Rule(
        head="nd24efb1fd42c496f9d5a1c31df55f73d(X)",
        body=("assignment(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r93"
    ))
    theory.add_rule(Rule(
        head="nbc9bf7cb71f14a789a4dcb9e4b1c9274(X)",
        body=("assignment(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r94"
    ))
    theory.add_rule(Rule(
        head="public_act(X)",
        body=("assignment(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r95"
    ))
    theory.add_rule(Rule(
        head="legal_speech_act(X)",
        body=("assignment(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r96"
    ))
    theory.add_rule(Rule(
        head="organisation(X)",
        body=("legal_person(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r97"
    ))
    theory.add_rule(Rule(
        head="corporation(X)",
        body=("foundation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r98"
    ))
    theory.add_rule(Rule(
        head="corporation(X)",
        body=("incorporated(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r99"
    ))
    theory.add_rule(Rule(
        head="corporation(X)",
        body=("unincorporated(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r100"
    ))
    theory.add_rule(Rule(
        head="society(X)",
        body=("co_operative(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r101"
    ))
    theory.add_rule(Rule(
        head="public_body(X)",
        body=("legislative_body(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r102"
    ))
    theory.add_rule(Rule(
        head="nd9ddc2b0fe394e44b55078697e734afd(X)",
        body=("decision(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r103"
    ))
    theory.add_rule(Rule(
        head="nb4192f4f92d4474ea72acda05a62378b(X)",
        body=("decision(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r104"
    ))
    theory.add_rule(Rule(
        head="legal_speech_act(X)",
        body=("decision(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r105"
    ))
    theory.add_rule(Rule(
        head="n6cd933c0898b4a91824260d5009e39b6(X)",
        body=("decision(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r106"
    ))
    theory.add_rule(Rule(
        head="speech_act(X)",
        body=("legal_speech_act(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r107"
    ))
    theory.add_rule(Rule(
        head="action(X)",
        body=("public_act(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r108"
    ))
    theory.add_rule(Rule(
        head="legal_role(X)",
        body=("social_legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r109"
    ))
    theory.add_rule(Rule(
        head="social_role(X)",
        body=("social_legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r110"
    ))
    theory.add_rule(Rule(
        head="n5b00e8b46fa34818a82b2c49ec17281f(X)",
        body=("legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r111"
    ))
    theory.add_rule(Rule(
        head="ncd9f05a24a134a31bbfbfb8b7345bd82(X)",
        body=("legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r112"
    ))
    theory.add_rule(Rule(
        head="role(X)",
        body=("legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r113"
    ))
    theory.add_rule(Rule(
        head="social_legal_role(X)",
        body=("professional_legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r114"
    ))
    theory.add_rule(Rule(
        head="organisation_role(X)",
        body=("professional_legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r115"
    ))
    theory.add_rule(Rule(
        head="n70eb93702eca4e33bb4cce7a1a782623(X)",
        body=("professional_legal_role(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r116"
    ))
    theory.add_rule(Rule(
        head="n68392d219bca4a778558c8e4fd283738(X)",
        body=("action(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r117"
    ))
    theory.add_rule(Rule(
        head="nefb4ad5ebd374bd687ed89dba083446c(X)",
        body=("action(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r118"
    ))
    theory.add_rule(Rule(
        head="process(X)",
        body=("action(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r119"
    ))
    theory.add_rule(Rule(
        head="n01a8061616a54586b6fe2205aaa8a55e(X)",
        body=("action(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r120"
    ))
    theory.add_rule(Rule(
        head="thing(X)",
        body=("agent(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r121"
    ))
    theory.add_rule(Rule(
        head="n49469edb5f3b499285afff0bfe5aff4d(X)",
        body=("agent(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r122"
    ))
    theory.add_rule(Rule(
        head="n2dfc14635b9744d191efbccd67f6f7a5(X)",
        body=("agent(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r123"
    ))
    theory.add_rule(Rule(
        head="n0e641d65bcce4c35aea78a84794d1826(X)",
        body=("agent(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r124"
    ))
    theory.add_rule(Rule(
        head="nc9ca455b1f7c4330bcfed9d4ddc965bd(X)",
        body=("reaction(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r125"
    ))
    theory.add_rule(Rule(
        head="action(X)",
        body=("reaction(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r126"
    ))
    theory.add_rule(Rule(
        head="reason(X)",
        body=("argument(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r127"
    ))
    theory.add_rule(Rule(
        head="neb56410082244997a05342cc95b8d911(X)",
        body=("argument(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r128"
    ))
    theory.add_rule(Rule(
        head="communicated_attitude(X)",
        body=("assertion(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r129"
    ))
    theory.add_rule(Rule(
        head="communicated_attitude(X)",
        body=("declaration(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r130"
    ))
    theory.add_rule(Rule(
        head="communicated_attitude(X)",
        body=("promise(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r131"
    ))
    theory.add_rule(Rule(
        head="na451cdb46b8949bdb89bc0e44d17b5ad(X)",
        body=("statement_in_writing(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r132"
    ))
    theory.add_rule(Rule(
        head="communicated_attitude(X)",
        body=("statement_in_writing(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r133"
    ))
    theory.add_rule(Rule(
        head="n4c40d8d13ce74080985a4b46a52beff0(X)",
        body=("assumption(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r134"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("assumption(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r135"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("cause(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r136"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("evidence(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r137"
    ))
    theory.add_rule(Rule(
        head="nba9011f571e14131825127c87b837825(X)",
        body=("evidence(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r138"
    ))
    theory.add_rule(Rule(
        head="n371abac6bede4510b7ce0cc36bea7537(X)",
        body=("exception(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r139"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("exception(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r140"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("expectation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r141"
    ))
    theory.add_rule(Rule(
        head="n71ee5b69ebe240ea95aaeae0bde12cbd(X)",
        body=("expectation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r142"
    ))
    theory.add_rule(Rule(
        head="na762953666d747f5b41ae34afa07ed67(X)",
        body=("expectation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r143"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("fact(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r144"
    ))
    theory.add_rule(Rule(
        head="naeef76b205be4b51a3bd8ea4b83e3d19(X)",
        body=("fact(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r145"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("observation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r146"
    ))
    theory.add_rule(Rule(
        head="n052d4749b45742259ce6483653e57f57(X)",
        body=("reason(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r147"
    ))
    theory.add_rule(Rule(
        head="epistemic_role(X)",
        body=("reason(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r148"
    ))
    theory.add_rule(Rule(
        head="propositional_attitude(X)",
        body=("belief(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r149"
    ))
    theory.add_rule(Rule(
        head="na28337e63695488e8e81cba42d424748(X)",
        body=("belief(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r150"
    ))
    theory.add_rule(Rule(
        head="propositional_attitude(X)",
        body=("communicated_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r151"
    ))
    theory.add_rule(Rule(
        head="nc0eda432d9de4884a3bf080e830ed62b(X)",
        body=("communicated_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r152"
    ))
    theory.add_rule(Rule(
        head="n23cff4b0469d4ffda378621a456f1ef0(X)",
        body=("communicated_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r153"
    ))
    theory.add_rule(Rule(
        head="nb976cc07d34b4d79b6fc44b776e00a86(X)",
        body=("communicated_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r154"
    ))
    theory.add_rule(Rule(
        head="nff6e1286cd034ed0ba992119ba3b4819(X)",
        body=("communicated_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r155"
    ))
    theory.add_rule(Rule(
        head="propositional_attitude(X)",
        body=("desire(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r156"
    ))
    theory.add_rule(Rule(
        head="propositional_attitude(X)",
        body=("evaluative_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r157"
    ))
    theory.add_rule(Rule(
        head="n6261c1ba90504666bf8c8191575f063f(X)",
        body=("evaluative_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r158"
    ))
    theory.add_rule(Rule(
        head="propositional_attitude(X)",
        body=("intention(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r159"
    ))
    theory.add_rule(Rule(
        head="nc9b18f807d0d49dc9b428ce1f079a655(X)",
        body=("intention(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r160"
    ))
    theory.add_rule(Rule(
        head="nb23fbb45df3e4397a94bd7c5c6adfc89(X)",
        body=("document(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r161"
    ))
    theory.add_rule(Rule(
        head="medium(X)",
        body=("document(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r162"
    ))
    theory.add_rule(Rule(
        head="proposition(X)",
        body=("evaluative_proposition(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r163"
    ))
    theory.add_rule(Rule(
        head="nc32ac5afdeea4387b65d165f9efd207b(X)",
        body=("evaluative_proposition(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r164"
    ))
    theory.add_rule(Rule(
        head="n0a26a078c66a4b59b26c106a0140ea4d(X)",
        body=("evaluative_proposition(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r165"
    ))
    theory.add_rule(Rule(
        head="ncb5a975725094e0dad10f3d3e0171b3c(X)",
        body=("expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r166"
    ))
    theory.add_rule(Rule(
        head="proposition(X)",
        body=("expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r167"
    ))
    theory.add_rule(Rule(
        head="nfe8decf3ce954fb795f59f5acbeccc73(X)",
        body=("expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r168"
    ))
    theory.add_rule(Rule(
        head="n33e621dbba5f45ada52bffe134849c70(X)",
        body=("expression(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r169"
    ))
    theory.add_rule(Rule(
        head="assertion(X)",
        body=("lie(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r170"
    ))
    theory.add_rule(Rule(
        head="thing(X)",
        body=("medium(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r171"
    ))
    theory.add_rule(Rule(
        head="n4d48fc6d53284b749a862783da9de0bb(X)",
        body=("medium(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r172"
    ))
    theory.add_rule(Rule(
        head="thing(X)",
        body=("qualified(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r173"
    ))
    theory.add_rule(Rule(
        head="na2fdc8883a134643a09572a56db6dca5(X)",
        body=("qualified(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r174"
    ))
    theory.add_rule(Rule(
        head="na7ba22e6e7cd4f069ac8fe9d5c03bf1c(X)",
        body=("qualified(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r175"
    ))
    theory.add_rule(Rule(
        head="observation(X)",
        body=("problem(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r176"
    ))
    theory.add_rule(Rule(
        head="observation(X)",
        body=("surprise(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r177"
    ))
    theory.add_rule(Rule(
        head="nc4692a40ccbe470a981376d1aec8b9ea(X)",
        body=("proposition(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r178"
    ))
    theory.add_rule(Rule(
        head="mental_object(X)",
        body=("proposition(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r179"
    ))
    theory.add_rule(Rule(
        head="ne9516590e4944007abc5ebac16533559(X)",
        body=("propositional_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r180"
    ))
    theory.add_rule(Rule(
        head="mental_object(X)",
        body=("propositional_attitude(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r181"
    ))
    theory.add_rule(Rule(
        head="n294d77f0ed7549c899f2dfd1bbbfe605(X)",
        body=("qualification(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r182"
    ))
    theory.add_rule(Rule(
        head="mental_object(X)",
        body=("qualification(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r183"
    ))
    theory.add_rule(Rule(
        head="creation(X)",
        body=("speech_act(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r184"
    ))
    theory.add_rule(Rule(
        head="n6ac88b5e08764b6a99f67da8fde164cb(X)",
        body=("mental_object(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r185"
    ))
    theory.add_rule(Rule(
        head="physical_object(X)",
        body=("artifact(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r186"
    ))
    theory.add_rule(Rule(
        head="physical_object(X)",
        body=("natural_object(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r187"
    ))
    theory.add_rule(Rule(
        head="plan(X)",
        body=("collaborative_plan(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r188"
    ))
    theory.add_rule(Rule(
        head="plan(X)",
        body=("personal_plan(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r189"
    ))
    theory.add_rule(Rule(
        head="action(X)",
        body=("creation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r190"
    ))
    theory.add_rule(Rule(
        head="n0b41473d2bbd4a7280a197a7f34b2a65(X)",
        body=("organisation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r191"
    ))
    theory.add_rule(Rule(
        head="agent(X)",
        body=("organisation(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r192"
    ))
    theory.add_rule(Rule(
        head="agent(X)",
        body=("person(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r193"
    ))
    theory.add_rule(Rule(
        head="natural_object(X)",
        body=("person(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r194"
    ))
    theory.add_rule(Rule(
        head="n13fdcbd1c78047178eb1606d81e72dba(X)",
        body=("plan(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r195"
    ))
    theory.add_rule(Rule(
        head="mental_object(X)",
        body=("plan(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r196"
    ))
    theory.add_rule(Rule(
        head="transaction(X)",
        body=("trade(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r197"
    ))
    theory.add_rule(Rule(
        head="n0f46d35dc7a34924b377e45d94fba19b(X)",
        body=("transaction(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r198"
    ))
    theory.add_rule(Rule(
        head="collaborative_plan(X)",
        body=("transaction(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r199"
    ))
    theory.add_rule(Rule(
        head="n46154578afb54d8ab3683a59af158294(X)",
        body=("transaction(X)",),
        rule_type=RuleType.STRICT,
        label="lkif_r200"
    ))

    return theory
