"""
WordNet Biology - Extracted Taxonomy

Extracted from WordNet 3.0 (Princeton University experts).
Taxonomic rules: 334
Behavioral predicates: 8

Citation: Miller, G. A. (1995). WordNet: A lexical database for English.

Author: Extracted by Patrick Cooper
Date: 2026-02-12
"""

from blanc.core.theory import Theory, Rule, RuleType


def create_wordnet_biology() -> Theory:
    """Create WordNet-extracted biology taxonomy."""
    theory = Theory()

    theory.add_rule(Rule(
        head="organism(X)",
        body=("diploid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r0"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("parent(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r1"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("clone(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r2"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("animal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r3"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("denizen(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r4"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("stander(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r5"
    ))
    theory.add_rule(Rule(
        head="causal_agent(X)",
        body=("person(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r6"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("person(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r7"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("zooid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r8"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("dwarf(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r9"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("relict(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r10"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("prokaryote(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r11"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("nekton(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r12"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("animalcule(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r13"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("katharobe(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r14"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("myrmecophile(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r15"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("saprobe(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r16"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("relative(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r17"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("host(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r18"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("heterotroph(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r19"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("postdiluvian(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r20"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("plankton(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r21"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("microorganism(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r22"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("sitter(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r23"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("heteroploid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r24"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("individual(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r25"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("hybrid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r26"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("eukaryote(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r27"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("commensal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r28"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("haploid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r29"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("parasite(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r30"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("fungus(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r31"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("polymorph(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r32"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("nonvascular_organism(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r33"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("conspecific(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r34"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("carrier(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r35"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("polyploid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r36"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("amphidiploid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r37"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("mascot(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r38"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("utterer(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r39"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("saprophyte(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r40"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("plant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r41"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("aerobe(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r42"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("recombinant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r43"
    ))
    theory.add_rule(Rule(
        head="cell(X)",
        body=("recombinant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r44"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("anaerobe(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r45"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("atavist(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r46"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("mutant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r47"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("benthos(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r48"
    ))
    theory.add_rule(Rule(
        head="organism(X)",
        body=("native(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r49"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("stunt(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r50"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("zooplankton(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r51"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("larva(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r52"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("pet(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r53"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("poikilotherm(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r54"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("acrodont(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r55"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("creepy_crawly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r56"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("giant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r57"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("homeotherm(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r58"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("varmint(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r59"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("marine_animal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r60"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("adult(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r61"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("scavenger(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r62"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("male(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r63"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("embryo(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r64"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("migrator(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r65"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("invertebrate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r66"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("mutant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r67"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("omnivore(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r68"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("herbivore(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r69"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("game(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r70"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("prey(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r71"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("insectivore(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r72"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("fictional_animal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r73"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("domestic_animal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r74"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("range_animal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r75"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("work_animal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r76"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("feeder(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r77"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("peeper(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r78"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("female(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r79"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("predator(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r80"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("molter(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r81"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("metazoan(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r82"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("captive(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r83"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("biped(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r84"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("racer(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r85"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("hexapod(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r86"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("thoroughbred(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r87"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("chordate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r88"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("critter(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r89"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("survivor(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r90"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("mate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r91"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("darter(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r92"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("stayer(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r93"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("pleurodont(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r94"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("young(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r95"
    ))
    theory.add_rule(Rule(
        head="animal(X)",
        body=("pest(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r96"
    ))
    theory.add_rule(Rule(
        head="larva(X)",
        body=("hellgrammiate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r97"
    ))
    theory.add_rule(Rule(
        head="larva(X)",
        body=("strawworm(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r98"
    ))
    theory.add_rule(Rule(
        head="larva(X)",
        body=("caseworm(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r99"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("twitterer(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r100"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("apodiform_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r101"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("hen(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r102"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("cuculiform_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r103"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("nester(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r104"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("ratite(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r105"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("caprimulgiform_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r106"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("passerine(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r107"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("coraciiform_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r108"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("dickeybird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r109"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("night_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r110"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("parrot(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r111"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("nonpasserine_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r112"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("sinornis(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r113"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("gallinaceous_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r114"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("ibero_mesornis(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r115"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("piciform_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r116"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("bird_of_prey(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r117"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("bird_of_passage(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r118"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("trogon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r119"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("archaeopteryx(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r120"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("cock(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r121"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("carinate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r122"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("aquatic_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r123"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("protoavis(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r124"
    ))
    theory.add_rule(Rule(
        head="bird(X)",
        body=("archaeornis(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r125"
    ))
    theory.add_rule(Rule(
        head="apodiform_bird(X)",
        body=("tree_swift(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r126"
    ))
    theory.add_rule(Rule(
        head="apodiform_bird(X)",
        body=("swift(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r127"
    ))
    theory.add_rule(Rule(
        head="apodiform_bird(X)",
        body=("hummingbird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r128"
    ))
    theory.add_rule(Rule(
        head="cuculiform_bird(X)",
        body=("touraco(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r129"
    ))
    theory.add_rule(Rule(
        head="cuculiform_bird(X)",
        body=("cuckoo(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r130"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("emu(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r131"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("rhea(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r132"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("elephant_bird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r133"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("rhea(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r134"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("cassowary(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r135"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("kiwi(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r136"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("moa(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r137"
    ))
    theory.add_rule(Rule(
        head="ratite(X)",
        body=("ostrich(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r138"
    ))
    theory.add_rule(Rule(
        head="caprimulgiform_bird(X)",
        body=("goatsucker(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r139"
    ))
    theory.add_rule(Rule(
        head="caprimulgiform_bird(X)",
        body=("frogmouth(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r140"
    ))
    theory.add_rule(Rule(
        head="caprimulgiform_bird(X)",
        body=("oilbird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r141"
    ))
    theory.add_rule(Rule(
        head="passerine(X)",
        body=("oscine(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r142"
    ))
    theory.add_rule(Rule(
        head="passerine(X)",
        body=("lyrebird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r143"
    ))
    theory.add_rule(Rule(
        head="passerine(X)",
        body=("sparrow(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r144"
    ))
    theory.add_rule(Rule(
        head="passerine(X)",
        body=("tyrannid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r145"
    ))
    theory.add_rule(Rule(
        head="passerine(X)",
        body=("broadbill(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r146"
    ))
    theory.add_rule(Rule(
        head="passerine(X)",
        body=("scrubbird(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r147"
    ))
    theory.add_rule(Rule(
        head="passerine(X)",
        body=("wren(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r148"
    ))
    theory.add_rule(Rule(
        head="coraciiform_bird(X)",
        body=("hornbill(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r149"
    ))
    theory.add_rule(Rule(
        head="mammal(X)",
        body=("prototherian(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r150"
    ))
    theory.add_rule(Rule(
        head="mammal(X)",
        body=("fossorial_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r151"
    ))
    theory.add_rule(Rule(
        head="mammal(X)",
        body=("placental(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r152"
    ))
    theory.add_rule(Rule(
        head="mammal(X)",
        body=("metatherian(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r153"
    ))
    theory.add_rule(Rule(
        head="mammal(X)",
        body=("tusker(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r154"
    ))
    theory.add_rule(Rule(
        head="mammal(X)",
        body=("female_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r155"
    ))
    theory.add_rule(Rule(
        head="female(X)",
        body=("female_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r156"
    ))
    theory.add_rule(Rule(
        head="prototherian(X)",
        body=("monotreme(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r157"
    ))
    theory.add_rule(Rule(
        head="fossorial_mammal(X)",
        body=("damaraland_mole_rat(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r158"
    ))
    theory.add_rule(Rule(
        head="fossorial_mammal(X)",
        body=("naked_mole_rat(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r159"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("pachyderm(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r160"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("carnivore(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r161"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("bat(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r162"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("cow(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r163"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("unguiculata(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r164"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("edentate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r165"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("pangolin(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r166"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("insectivore(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r167"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("lagomorph(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r168"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("fissipedia(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r169"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("aardvark(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r170"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("rodent(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r171"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("unguiculate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r172"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("primate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r173"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("tree_shrew(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r174"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("aquatic_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r175"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("doe(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r176"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("ungulate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r177"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("livestock(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r178"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("buck(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r179"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("ungulata(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r180"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("plantigrade_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r181"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("bull(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r182"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("flying_lemur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r183"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("hyrax(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r184"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("yearling(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r185"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("digitigrade_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r186"
    ))
    theory.add_rule(Rule(
        head="placental(X)",
        body=("proboscidean(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r187"
    ))
    theory.add_rule(Rule(
        head="metatherian(X)",
        body=("marsupial(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r188"
    ))
    theory.add_rule(Rule(
        head="monotreme(X)",
        body=("echidna(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r189"
    ))
    theory.add_rule(Rule(
        head="monotreme(X)",
        body=("platypus(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r190"
    ))
    theory.add_rule(Rule(
        head="monotreme(X)",
        body=("echidna(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r191"
    ))
    theory.add_rule(Rule(
        head="naked_mole_rat(X)",
        body=("queen(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r192"
    ))
    theory.add_rule(Rule(
        head="pachyderm(X)",
        body=("elephant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r193"
    ))
    theory.add_rule(Rule(
        head="proboscidean(X)",
        body=("elephant(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r194"
    ))
    theory.add_rule(Rule(
        head="carnivore(X)",
        body=("procyonid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r195"
    ))
    theory.add_rule(Rule(
        head="carnivore(X)",
        body=("bear(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r196"
    ))
    theory.add_rule(Rule(
        head="carnivore(X)",
        body=("feline(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r197"
    ))
    theory.add_rule(Rule(
        head="carnivore(X)",
        body=("fissiped_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r198"
    ))
    theory.add_rule(Rule(
        head="carnivore(X)",
        body=("canine(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r199"
    ))
    theory.add_rule(Rule(
        head="carnivore(X)",
        body=("musteline_mammal(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r200"
    ))
    theory.add_rule(Rule(
        head="carnivore(X)",
        body=("viverrine(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r201"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("panfish(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r202"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("schrod(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r203"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("smelt(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r204"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("haddock(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r205"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("eel(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r206"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("trout(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r207"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("stockfish(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r208"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r209"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("shad(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r210"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("alewife(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r211"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("anchovy(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r212"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("rock_salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r213"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("hake(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r214"
    ))
    theory.add_rule(Rule(
        head="fish(X)",
        body=("mullet(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r215"
    ))
    theory.add_rule(Rule(
        head="smelt(X)",
        body=("european_smelt(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r216"
    ))
    theory.add_rule(Rule(
        head="smelt(X)",
        body=("american_smelt(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r217"
    ))
    theory.add_rule(Rule(
        head="haddock(X)",
        body=("finnan_haddie(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r218"
    ))
    theory.add_rule(Rule(
        head="eel(X)",
        body=("smoked_eel(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r219"
    ))
    theory.add_rule(Rule(
        head="eel(X)",
        body=("elver(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r220"
    ))
    theory.add_rule(Rule(
        head="trout(X)",
        body=("sea_trout(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r221"
    ))
    theory.add_rule(Rule(
        head="trout(X)",
        body=("rainbow_trout(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r222"
    ))
    theory.add_rule(Rule(
        head="salmon(X)",
        body=("atlantic_salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r223"
    ))
    theory.add_rule(Rule(
        head="salmon(X)",
        body=("silver_salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r224"
    ))
    theory.add_rule(Rule(
        head="salmon(X)",
        body=("red_salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r225"
    ))
    theory.add_rule(Rule(
        head="salmon(X)",
        body=("kippered_salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r226"
    ))
    theory.add_rule(Rule(
        head="salmon(X)",
        body=("chinook_salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r227"
    ))
    theory.add_rule(Rule(
        head="salmon(X)",
        body=("smoked_salmon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r228"
    ))
    theory.add_rule(Rule(
        head="smoked_salmon(X)",
        body=("lox(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r229"
    ))
    theory.add_rule(Rule(
        head="lox(X)",
        body=("scandinavian_lox(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r230"
    ))
    theory.add_rule(Rule(
        head="lox(X)",
        body=("nova_scotia_lox(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r231"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("imago(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r232"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("neuropteron(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r233"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("trichopterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r234"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("dipterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r235"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("leaf_miner(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r236"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("louse(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r237"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("collembolan(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r238"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("worker(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r239"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("hemipterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r240"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("psocopterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r241"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("dictyopterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r242"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("pollinator(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r243"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("mecopteran(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r244"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("ephemerid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r245"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("holometabola(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r246"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("defoliator(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r247"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("gallfly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r248"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("earwig(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r249"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("queen(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r250"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("homopterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r251"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("stonefly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r252"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("proturan(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r253"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("bug(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r254"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("heteropterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r255"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("social_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r256"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("odonate(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r257"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("lepidopterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r258"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("ephemeron(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r259"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("flea(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r260"
    ))
    theory.add_rule(Rule(
        head="ectoparasite(X)",
        body=("flea(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r261"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("hymenopterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r262"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("orthopterous_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r263"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("phasmid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r264"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("beetle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r265"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("termite(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r266"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("bird_louse(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r267"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("thysanuran_insect(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r268"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("thysanopter(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r269"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("pupa(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r270"
    ))
    theory.add_rule(Rule(
        head="insect(X)",
        body=("web_spinner(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r271"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("lacewing(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r272"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("dobson(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r273"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("ant_lion(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r274"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("mantispid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r275"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("spongefly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r276"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("fish_fly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r277"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("alderfly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r278"
    ))
    theory.add_rule(Rule(
        head="neuropteron(X)",
        body=("snakefly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r279"
    ))
    theory.add_rule(Rule(
        head="trichopterous_insect(X)",
        body=("caddis_fly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r280"
    ))
    theory.add_rule(Rule(
        head="dipterous_insect(X)",
        body=("gall_midge(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r281"
    ))
    theory.add_rule(Rule(
        head="dipterous_insect(X)",
        body=("fly(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r282"
    ))
    theory.add_rule(Rule(
        head="reptile(X)",
        body=("diapsida(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r283"
    ))
    theory.add_rule(Rule(
        head="reptile(X)",
        body=("anapsid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r284"
    ))
    theory.add_rule(Rule(
        head="reptile(X)",
        body=("diapsid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r285"
    ))
    theory.add_rule(Rule(
        head="reptile(X)",
        body=("synapsid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r286"
    ))
    theory.add_rule(Rule(
        head="anapsid(X)",
        body=("chelonian(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r287"
    ))
    theory.add_rule(Rule(
        head="diapsid(X)",
        body=("archosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r288"
    ))
    theory.add_rule(Rule(
        head="diapsid(X)",
        body=("snake(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r289"
    ))
    theory.add_rule(Rule(
        head="diapsid(X)",
        body=("tuatara(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r290"
    ))
    theory.add_rule(Rule(
        head="diapsid(X)",
        body=("saurian(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r291"
    ))
    theory.add_rule(Rule(
        head="diapsid(X)",
        body=("crocodilian_reptile(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r292"
    ))
    theory.add_rule(Rule(
        head="synapsid(X)",
        body=("ictodosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r293"
    ))
    theory.add_rule(Rule(
        head="synapsid(X)",
        body=("dimetrodon(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r294"
    ))
    theory.add_rule(Rule(
        head="synapsid(X)",
        body=("edaphosaurus(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r295"
    ))
    theory.add_rule(Rule(
        head="synapsid(X)",
        body=("pelycosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r296"
    ))
    theory.add_rule(Rule(
        head="synapsid(X)",
        body=("therapsid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r297"
    ))
    theory.add_rule(Rule(
        head="chelonian(X)",
        body=("turtle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r298"
    ))
    theory.add_rule(Rule(
        head="archosaur(X)",
        body=("dinosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r299"
    ))
    theory.add_rule(Rule(
        head="archosaur(X)",
        body=("thecodont(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r300"
    ))
    theory.add_rule(Rule(
        head="archosaur(X)",
        body=("nothosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r301"
    ))
    theory.add_rule(Rule(
        head="archosaur(X)",
        body=("pterosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r302"
    ))
    theory.add_rule(Rule(
        head="archosaur(X)",
        body=("plesiosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r303"
    ))
    theory.add_rule(Rule(
        head="archosaur(X)",
        body=("ichthyosaur(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r304"
    ))
    theory.add_rule(Rule(
        head="snake(X)",
        body=("sea_snake(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r305"
    ))
    theory.add_rule(Rule(
        head="snake(X)",
        body=("constrictor(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r306"
    ))
    theory.add_rule(Rule(
        head="snake(X)",
        body=("viper(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r307"
    ))
    theory.add_rule(Rule(
        head="snake(X)",
        body=("colubrid_snake(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r308"
    ))
    theory.add_rule(Rule(
        head="snake(X)",
        body=("blind_snake(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r309"
    ))
    theory.add_rule(Rule(
        head="snake(X)",
        body=("elapid(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r310"
    ))
    theory.add_rule(Rule(
        head="saurian(X)",
        body=("lizard(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r311"
    ))
    theory.add_rule(Rule(
        head="crocodilian_reptile(X)",
        body=("gavial(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r312"
    ))
    theory.add_rule(Rule(
        head="crocodilian_reptile(X)",
        body=("crocodile(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r313"
    ))
    theory.add_rule(Rule(
        head="crocodilian_reptile(X)",
        body=("false_gavial(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r314"
    ))
    theory.add_rule(Rule(
        head="crocodilian_reptile(X)",
        body=("alligator(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r315"
    ))
    theory.add_rule(Rule(
        head="crocodilian_reptile(X)",
        body=("caiman(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r316"
    ))
    theory.add_rule(Rule(
        head="therapsid(X)",
        body=("chronoperates_paradoxus(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r317"
    ))
    theory.add_rule(Rule(
        head="therapsid(X)",
        body=("cynodont(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r318"
    ))
    theory.add_rule(Rule(
        head="therapsid(X)",
        body=("dicynodont(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r319"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("painted_turtle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r320"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("snapping_turtle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r321"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("red_bellied_terrapin(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r322"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("cooter(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r323"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("box_turtle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r324"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("soft_shelled_turtle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r325"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("mud_turtle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r326"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("sea_turtle(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r327"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("terrapin(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r328"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("tortoise(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r329"
    ))
    theory.add_rule(Rule(
        head="turtle(X)",
        body=("slider(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r330"
    ))
    theory.add_rule(Rule(
        head="dinosaur(X)",
        body=("diplodocus(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r331"
    ))
    theory.add_rule(Rule(
        head="dinosaur(X)",
        body=("ornithischian(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r332"
    ))
    theory.add_rule(Rule(
        head="amphibian(X)",
        body=("swamp_buggy(X)",),
        rule_type=RuleType.STRICT,
        label="wn_r333"
    ))

    return theory


# Behavioral predicates extracted:
# - fly/1
# - swim/1
# - walk/1
# - run/1
# - hunt/1
# - eat/1
# - migrate/1
# - sing/1
